url: "https://tomoaki-kimura.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "HearthSide KidsPrograming School" # the name of your site, e.g. ACME Corp.

courses:
  basic:
    - スクラッチ
    - Ruby(1)
    - Ruby2D(1)
  standard:
    - 開発環境(1)
    - 開発環境(2)
    - Ruby(1)
    - Ruby2D(1)
    - Ruby_2(2)
    - Ruby2D(2)
  advance:
    - 開発環境(1)
    - HTML/CSS
    - CSS
    - 開発環境(2)
  professional:
    - 開発環境(1)
    - HTML/CSS

page_excepts: true

curriculums:
  - title: スクラッチ
    icon: lo-scratch-line
    part: scratch
    contents:
      - title: 迷路ゲーム
        chapter: meiro
      - title: ジャンプゲーム
        chapter: jump_game
      - title: ヘビゲーム
        chapter: hebi
  - title: 開発環境(1)
    icon: ri-computer-line
    part: davelopent_environment
    contents:
      - title: VSCode
        chapter: vs_code
      - title: Git
        chapter: git
  - title: HTML/CSS
    icon: ri-html5-line
    part: html_css
    contents:
      - title: HTML
        chapter: html
      - title: CSS
        chapter: css  
      - title: webサイト
        chapter: my_site
  - title: CSS
    icon: ri-css3-line
    part: css
    contents:
      - title: ２カラムデザイン
        chapter: two_column
      - title: パネルデザイン
        chapter: panel
      - title: フォーム
        chapter: form
      - title: レスポンシブデザイン
        chapter: response
  - title: JavaScript(1)
    icon: ri-javascript-line
    part: javescript
    contents:
      - title: JavaScript基礎
        chapter: java_script_basic
      - title: シングルページ
        chapter: single_page
  - title: 開発環境(2)
    icon: ri-computer-line
    part: davelopent_environment
    contents:
      - title: WSL
        chapter: wsl
      - title: asdf
        chapter: asdf
  - title: Ruby(1)
    icon: lo-ruby-line
    part: ruby
    contents:
      - title: ruby基礎
        chapter: ruby_basic
      - title: RubyGems
        chapter: ruby_gems
  - title: Rspec(1)
    icon: lo-ruby-line
    part: rspec
  - title: WebAssembly
    icon: lo-ruby-line
    part: wasm
  - title: Git
    icon: ri-git-branch-line
    part: git
    contents:
      - title: Git基礎
        chapter: git
      - title: github.io
        chapter: git
  - title: Ruby2D(1)
    icon: lo-ruby-line
    part: ruby2d
    contents:
      - title: 基礎
        chapter: ruby2d_basic
      - title: ヘビゲーム
        chapter: hebi
  - title: Ruby(2)
    icon: lo-ruby-line
    part: ruby
    contents:
      - title: Ruby応用
        chapter: ruby_advance
  - title: Ruby2D(2)
    icon: lo-ruby-line
    part: ruby2d
    contents:
      - title: ブロックくずし
        chapter: blocks
      - title: シューティングゲーム
        chapter: ruby.html
      - title: テトリス
        chapter: ruby.html
  - title: Github
    icon: ri-github-line
    part: github
    contents:
      - title: Github基礎
        chapter: link
  - title: Jekyll
    icon: lo-jekyll-line
    part: jekll
    contents:
      - title: ブログサイト
        chapter: ruby
      - title: webサイトのリプレイス
        chapter: ruby
  - title: sinatra
    icon: lo-sinatra-line
    part: sinatra
    contents:
      - title: 時間割
        chapter: ruby
      - title: Api
        chapter: ruby
  - title: SQL(1)
    icon: ri-database-2-line
    part: sql
    contents:
      - title: SQLite
        chapter: ruby.html
      - title: 時間割（２）
        chapter: ruby.html
  - title: RubyOnRails(1)
    icon: lo-rails-line
    part: ruby_on_rails
    contents:
      - title: タスクリスト
        chapter: tasklist
      - title: SNS
        chapter: link
  - title: JavaScript(2)
    icon: ri-javascript-line
    part: javescript
    contents:
      - title: TypeScript
        chapter: link
      - title: Stimulus
        chapter: stimulus
  - title: SQL(2)
    icon: ri-database-2-line
    part: sql_2
    contents:
      - title: PostgreSQL
        chapter: link
  - title: 設計
    icon: ri-file-line
    part: app_design
    contents:
      - title: 企画書
        chapter: kikaku
      - title: 画面遷移図
        chapter: senizu
      - title: 画面詳細図
        chapter: shousai
      - title: ER図
        chapter: er
      - title: テーブル設計書
        chapter: teble
      - title: URL設計書
        chapter: url
      - title: 要件定義書
        chapter: youken
  - title: RubyOnRails(2)
    icon: lo-rails-line
    contents:
      - title: ECサイト
        chapter: tasklist
  - title: 本番環境(1)
    icon: ri-server-line
    contents:
      - title: AWS
        chapter: link
  - title: 卒業制作
    icon: ri-layout-5-line
    contents:
      - title: 企画
        chapter: kikaku
      - title: 設計
        chapter: sekkei
      - title: 制作
        chapter: seisaku
      - title: デプロイ
        chapter: deploy
  - title: 本番環境(2)
    icon: ri-server-line
    contents:
      - title: ドメイン
        chapter: link
      - title: SSL
        chapter: link
      - title: 自動デプロイ
        chapter: link
