url: "https://tomoaki-kimura.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "HearthSide KidsPrograming School" # the name of your site, e.g. ACME Corp.


collections_dir: articles

collections:
  drafts:
    output: true
  html:
    output: true
  css:
    output: true
  bootstrap:
    output: true
  ruby:
    output: true
  ruby_2d:
    output: true
  jekyll:
    output: true
  ruby_on_rails:
    output: true

courses:
  - title: スクラッチ
    icon: lo-scratch-line
    contents:
      - title: 迷路ゲーム
        link: scratch.html
      - title: ジャンプゲーム
        link: scratch.html
      - title: ヘビゲーム
        link: scratch.html
  - title: 開発環境
    icon: ri-computer-line
    contents: 
      - title: VSCode
        link: vs_code.html
      - title: Git
        link: git.html
  - title: HTML/CSS
    icon: ri-html5-line
    contents:
      - title: HTML
        link: html_base.html
      - title: CSS
        link: html_tags.html  
      - title: webサイト
        link: my_site.html
  - title: CSS
    icon: ri-css3-line
    contents:
      - title: ２カラムデザイン
        link: column.html
      - title: パネルデザイン
        link: panel.html
      - title: フォーム
        link: form.html
      - title: レスポンシブデザイン
        link: response.html
  - title: JavaScript
    icon: ri-javascript-line
    contents:
      - title: JavaScript基礎
        link: java_script.html
      - title: シングルページ
        link: java_script.html
  - title: 開発環境(2)
    icon: ri-computer-line
    contents:
      - title: WSL
        link: wsl.html
      - title: asdf
        link: asdf.html
  - title: Ruby
    icon: lo-ruby-line
    contents:
      - title: ruby文法
        link: ruby.html
      - title: ライブラリ
        link: ruby.html
  - title: Git
    icon: ri-git-branch-line
    contents:
      - title: Git基礎
        link: git
  - title: Ruby2D
    icon: lo-ruby-line
    contents:
      - title: 基礎
        link: ruby2d.html
      - title: ヘビゲーム
        link: ruby.html
      - title: ブロック崩し
        link: ruby.html
      - title: シューティングゲーム
        link: ruby.html
      - title: テトリス
        link: ruby.html
  - title: Github
    icon: ri-github-line
    contents:
      - title: Github基礎
        link: link
  - title: Jekyll
    icon: lo-jekyll-line
    contents:
      - title: ブログサイト
        link: ruby.html
      - title: webサイトのリプレイス
        link: ruby.html
  - title: sinatra
    icon: lo-sinatra-line
    contents:
      - title: 時間割
        link: ruby.html
      - title: Api
        link: ruby.html
  - title: SQL
    icon: ri-database-2-line
    contents:
      - title: SQLite
        link: ruby.html
      - title: 時間割（２）
        link: ruby.html
  - title: NoSQL
    icon: ri-database-2-line
    contents:
      - title: Redis
        link: ruby.html
      - title: FireBase
        link: firebase
  - title: RubyOnRails
    icon: lo-rails-line
    contents:
      - title: タスクリスト
        link: tasklist
      - title: SNS
        link: link
  - title: JavaScript(2)
    icon: ri-javascript-line
    contents:
      - title: TypeScript
        link: link
      - title: Stimulus
        link: stimulus
  - title: SQL(2)
    icon: ri-database-2-line
    contents:
      - title: PostgreSQL
        link: link
  - title: 設計
    icon: ri-file-line
    contents:
      - title: 企画書
        link: kikaku
      - title: 画面遷移図
        link: senizu
      - title: 画面詳細図
        link: shousai
      - title: ER図
        link: er
      - title: テーブル設計書
        link: teble
      - title: URL設計書
        link: url
      - title: 要件定義書
        link: youken
  - title: RubyOnRails(2)
    icon: lo-rails-line
    contents:
      - title: ECサイト
        link: tasklist
  - title: 本番環境
    icon: ri-server-line
    contents:
      - title: AWS
        link: link
  - title: 卒業制作
    icon: ri-layout-5-line
    contents:
      - title: 企画
        link: kikaku
      - title: 設計
        link: sekkei
      - title: 制作
        link: seisaku
      - title: デプロイ
        link: deploy

classes:
  basic:
    contentes:
      - スクラッチ
      - 開発環境
      - 開発環境(2)

  advance: ""
  professional: ""
