url: "https://tomoaki-kimura.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "HearthSide KidsPrograming School" # the name of your site, e.g. ACME Corp.

collections_dir: articles

collections:
  drafts:
    output: true
  html:
    output: true
  css:
    output: true
  bootstrap:
    output: true
  ruby:
    output: true
  ruby_2d:
    output: true
  jekyll:
    output: true
  ruby_on_rails:
    output: true

header_pages:
  - title: 開発環境を整えよう(1)
    contents: 
      - title: VSCode
        link: vs_code.html
      - title: Git
        link: git.html
  - title: HTML/CSS
    contents:
      - title: HTML
        link: html_base.html
      - title: CSS
        link: html_tags.html
      - title: ウェブページ作成
        link: id_class
      - title: Bootstrap
        link:  
      - title: ウェブサイト作成
        link:
  - title: CSSフレームワーク
    contents:
      - title: Bootstrap
        link: bootstrap.html
        
  - title: JavaScript
  - title: 開発環境を整えよう(2)
  - title: Ruby基礎
  - title: Ruby応用
