url: "https://tomoaki-kimura.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "HearthSide KidsPrograming School" # the name of your site, e.g. ACME Corp.

courses:
  basic_course:
    - スクラッチ
    - Ruby(1)
  standard_course:
    - 開発環境(1)
    - 開発環境(2)
    - Ruby(1)
    - Ruby2D(1)
    - Ruby(2)
    - Ruby2D(2)
  advance_course:
    - 開発環境(1)
    - HTML/CSS
    - CSS
    - 開発環境(2)
  professional_course:
    - 開発環境(1)
    - HTML/CSS

collections_dir: articles

collections:
  scratch:
    output: true
  drafts:
    output: true
  davelopent_environment:
    output: true
  ruby:
    output: true
  ruby_2d:
    output: true

curriculums:
  - title: スクラッチ
    icon: lo-scratch-line
    link: scratch
    contents:
      - title: 迷路ゲーム
        params: meiro
      - title: ジャンプゲーム
        params: jump_game
      - title: ヘビゲーム
        params: hebi
  - title: 開発環境(1)
    icon: ri-computer-line
    link: davelopent_environment
    level: 1
    contents:
      - title: VSCode
        params: vs_code
      - title: Git
        params: git
  - title: HTML/CSS
    icon: ri-html5-line
    link: html_css
    contents:
      - title: HTML
        params: html
      - title: CSS
        params: css  
      - title: webサイト
        params: my_site
  - title: CSS
    icon: ri-css3-line
    link: css
    contents:
      - title: ２カラムデザイン
        params: two_column
      - title: パネルデザイン
        params: panel
      - title: フォーム
        params: form
      - title: レスポンシブデザイン
        params: response
  - title: JavaScript(1)
    icon: ri-javascript-line
    link: javescript
    level: 1
    contents:
      - title: JavaScript基礎
        params: java_script_basic
      - title: シングルページ
        params: single_page
  - title: 開発環境(2)
    icon: ri-computer-line
    link: davelopent_environment
    level: 2
    contents:
      - title: WSL
        params: wsl
      - title: asdf
        params: asdf
  - title: Ruby(1)
    icon: lo-ruby-line
    link: ruby
    level: 1
    contents:
      - title: ruby基礎
        params: ruby_basic
      - title: RubyGems
        params: ruby_gems
  - title: Rspec(1)
    icon: lo-ruby-line
    link: rspec
    level: 1
  - title: WebAssembly
    icon: lo-ruby-line
    link: wasm
  - title: Git
    icon: ri-git-branch-line
    link: git
    contents:
      - title: Git基礎
        params: git
      - title: github.io
        params: git
  - title: Ruby2D(1)
    icon: lo-ruby-line
    link: ruby2d
    level: 1
    contents:
      - title: 基礎
        params: ruby2d_basic
      - title: ヘビゲーム
        params: hebi
  - title: Ruby(2)
    icon: lo-ruby-line
    link: ruby
    level: 2
    contents:
      - title: Ruby応用
        params: ruby_advance
  - title: Ruby2D(2)
    icon: lo-ruby-line
    link: ruby2d
    level: 2
    contents:
      - title: ブロックくずし
        params: blocks
      - title: シューティングゲーム
        params: ruby.html
      - title: テトリス
        params: ruby.html
  - title: Github
    icon: ri-github-line
    link: github
    contents:
      - title: Github基礎
        params: link
  - title: Jekyll
    icon: lo-jekyll-line
    contents:
      - title: ブログサイト
        link: ruby.html
      - title: webサイトのリプレイス
        link: ruby.html
  - title: sinatra
    icon: lo-sinatra-line
    contents:
      - title: 時間割
        link: ruby.html
      - title: Api
        link: ruby.html
  - title: SQL(1)
    icon: ri-database-2-line
    contents:
      - title: SQLite
        link: ruby.html
      - title: 時間割（２）
        link: ruby.html
  - title: NoSQL
    icon: ri-database-2-line
    contents:
      - title: Redis
        link: ruby.html
      - title: FireBase
        link: firebase
  - title: RubyOnRails
    icon: lo-rails-line
    contents:
      - title: タスクリスト
        link: tasklist
      - title: SNS
        link: link
  - title: JavaScript(2)
    icon: ri-javascript-line
    contents:
      - title: TypeScript
        link: link
      - title: Stimulus
        link: stimulus
  - title: SQL(2)
    icon: ri-database-2-line
    contents:
      - title: PostgreSQL
        link: link
  - title: 設計
    icon: ri-file-line
    contents:
      - title: 企画書
        link: kikaku
      - title: 画面遷移図
        link: senizu
      - title: 画面詳細図
        link: shousai
      - title: ER図
        link: er
      - title: テーブル設計書
        link: teble
      - title: URL設計書
        link: url
      - title: 要件定義書
        link: youken
  - title: RubyOnRails(2)
    icon: lo-rails-line
    contents:
      - title: ECサイト
        link: tasklist
  - title: 本番環境
    icon: ri-server-line
    contents:
      - title: AWS
        link: link
  - title: 卒業制作
    icon: ri-layout-5-line
    contents:
      - title: 企画
        link: kikaku
      - title: 設計
        link: sekkei
      - title: 制作
        link: seisaku
      - title: デプロイ
        link: deploy

